### ISSUE TITLE
jump_next_indent does not work

### ISSUE THREAD

**Issue by lpww** [mwean/sublime_jump_along_indent#10]
Hey, I love the look of your plugin, it's exactly the functionality that I'm looking for! Unfortunately, I am having trouble with it, the jump_next_indent without highlighting does not work. All other functions work great:

* [x] { "keys": ["alt+up"], "command": "jump_prev_indent" }
* [x] { "keys": ["alt+shift+up"], "command": "jump_prev_indent", "args": { "extend_selection": true} }
* [ ] { "keys": ["alt+down"], "command": "jump_next_indent" }
* [x] { "keys": ["alt+shift+down"], "command": "jump_next_indent", "args": { "extend_selection": true} }

I'm using all default settings for the package on Sublime 3. 

I have 4 packages installed:

* Package Manager
* Babel
* Elm Language Support
* Jump Along Indent

I've tested on 4 different file types:

* JSON
* Javascript
* Plain Text
* Javascript (Babel)

These are my Sublime settings:

>{
	"binary_file_patterns":
	[
		// file patterns
	],
	"font_size": 12,
	"ignored_packages":
	[
		"Vintage"
	],
	"tab_size": 2,
	"translate_tabs_to_spaces": true,
	"trim_trailing_white_space_on_save": true
}

Any ideas what the issue could be? I thought maybe some kind of conflict with another package/setting but I have very little customization going on and nothing stands out to me.

**Comment by mwean** [comment]
Hi @lpww, that's pretty strange. The only issue I know of is that it doesn't deal with tabs correctly. The only thing I can think of is that another plugin or default command is using the same keybinding, so you could try the [FindKeyConflicts plugin](https://github.com/skuroda/FindKeyConflicts) to see if that's the case. I don't have time to investigate this right now, but I'll take a look this weekend.

**Comment by lpww** [comment]
Thanks for the message, @mwean. When you say it doesn't deal with tabs correctly are you talking about Sublime tabs (multiple files open) or tabs in text (tabs vs spaces)? I have a lot of Sublime tabs open but all my files and settings deal with spaces only. I'm pretty sure there was nothing bound to that keybinding before but I'll try the findkeyconflicts plugin and let you know if it helps.

**Comment by mwean** [comment]
Sorry, I meant leading tab characters in a file

**Comment by lpww** [comment]
@mwean FindKeyConflicts did the trick - there was a conflict with this package and the Elm Language Support. Thanks for help :)

**Comment by mwean** [comment]
Great to hear it! Let me know if you run into any other issues
